### ISSUE TITLE
Doesn't seem to work with Pygal 1.6.1

### ISSUE THREAD

**Issue by Resisty** [s3rvac/pygal-toggle-graphs#3]
I should note I haven't grabbed an older version of Pygal to try this with, but when I use your javascript (and thanks, by the way, for making this!), I can't toggle lines. Maybe it's relevant that I'm using a DateY graph?

```
custom_style = Style(
        background='transparent',
        plot_background='transparent',
        foreground='#000000',
        foreground_light='#585858',
        foreground_dark='#383838',
        opacity='.6',
        opacity_hover='.9',
        transition='400ms ease-in',
        colors=('#FF6600', '#9900CC', '#FF66FF'))
    js = [
      'http://kozea.github.com/pygal.js/javascripts/svg.jquery.js',     # Original
      'http://kozea.github.com/pygal.js/javascripts/pygal-tooltips.js', # Original
      'http://rawgit.com/s3rvac/pygal-toggle-graphs/master/pygal-toggle-graphs.js'
        ]

    datey = pygal.DateY(x_label_rotation=20,
                        title = 'Stuff',
                        x_title = 'Datetime',
                        include_x_axis = True,
                        print_values = False,
                        js = js,
                        style = custom_style)
```

**Comment by Resisty** [comment]
Nevermind, I'm dumb.

**Comment by Resisty** [comment]
Sorry for the opening/closing/reopening, but I'm not sure what I could be doing wrong. I'm embedding the svg from pygal straight from the render() method via a flask endpoint, running under wsgi/apache:

html:

```
<head>
    <script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/svg.jquery.js"></script>
    <script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/pygal-tooltips.js"></script>
    <script type="text/javascript" src="http://rawgit.com/s3rvac/pygal-toggle-graphs/master/pygal-toggle-graphs.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</head>
...
 <div id='svg'>
    <figure id='svg-fig'>
    </figure>
</div>
<script>
  $(function() {
      var data = $.get('/flaskendpoint', function(data) {
          $('#svg-fig').html(data);
      });
  });
</script>
```

pygal:

```
def make_datey():
    datey = pygal.DateY(x_label_rotation=20,
                    title = 'Piecewise Trends of Filtered Tweets Over Time',
                    x_title = 'Datetime',
                    include_x_axis = True,
                    print_values = False,
                    disable_xml_declaration = True,
                    style = custom_style)
    for flavor, flavor_data in data_by_flavor.iteritems():
        pygal_data = pygal_dateyify(flavor_data)
        datey.add(flavor, pygal_data)
    return datey
```

flask:

```
@app.route('/', methods=['GET'])
def plot():
    plot = make_datey()
    return plot.render()
```

The chart shows up as expected but I can't figure out how to get your javascript to load. Thanks very much for your time!

Details: Pygal 1.6.1, Flask 0.10.1, Google Chrome 41.0.2272.118 m

**Comment by s3rvac** [comment]
Hi! Thanks for the report. The `pygal-toggle-graphs` module works as follows. When the module is loaded, it searches through all graphs that are present in the page. For every found graph, it sets up on-click actions to enable toggling.

The problem is that you add the graph to the page dynamically through AJAX, which is done after the page is loaded. Therefore, upon page load, the module does not find any graphs and thus does not set any on-click actions.

I have added a possibility to re-initialize the module after a new graph is added to the page (commit f504671a8d50add2b90f816828e11ac1bd354bff). To do this, simply call `initPygalToggleGraphs()` after you load the graph. That is, replace

``` javascript
$('#svg-fig').html(data);
```

with

``` javascript
$('#svg-fig').html(data);
initPygalToggleGraphs();
```

I have tested this on pygal 1.6.1 and Google Chrome 41 and it works. Please, let me know if this fixes the problem for you.

**Comment by Resisty** [comment]
It does indeed! Works just like you said. Thanks for the quick turnaround!
